apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: events
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            demo: events
        spec:
          container:
            image: gcr.io/s9-demo/myevents:latest
            imagePullPolicy: Always
            env:
            - name: RELEASE
              value: "v0.2.4"
            - name: GCP_PROJECT_ID
              value: "s9-demo"