apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: events
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            demo: events
        spec:
          container:
            image: gcr.io/s9-demo/myevents:latest
            imagePullPolicy: Always
            env:
            - name: RELEASE
              value: "v0.2.6"
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: project